### ISSUE TITLE
Text Offset on Ballistic Range outputs wrong Y axis value

### ISSUE THREAD

**Issue by Faryzal2020** [SMILEY4/WTSightEdit#1]
![image](https://user-images.githubusercontent.com/8612170/54255283-c726ce00-459a-11e9-8949-d926c65ced79.png)
![image](https://user-images.githubusercontent.com/8612170/54255300-dc036180-459a-11e9-9bb0-79eb954801bc.png)
should be outputting 0 for the Y axis, but instead it takes the X axis value

**Comment by SMILEY4** [comment]
Thanks for reporting that bug.
It should be fixed now   :)
