### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by Boesergolf** [SMILEY4/WTSightEdit#3]
Downloaded the latest release but the java file wont start

**Comment by DrunkenTee** [comment]
same, wont start

**Comment by Jackaroo05** [comment]
Same

**Comment by Skektec** [comment]
I tried launching through Windows Powershell by using  `java .\WTSightEdit.jar` 
Error I got was:
```
Error: Could not find or load main class .\WTSightEdit.jar
Caused by: java.lang.ClassNotFoundException: /\WTSightEdit/jar
```
Any help will be appreciated.

**Comment by SMILEY4** [comment]
Hi @Skektec

the command to run a .jar file should be `java -jar .\WTSightEdit.jar`. There also seems to be another problem (with java?) independend from the jar-file and the programm.  Im looking into it.

**Comment by SMILEY4** [comment]
this project was developed with an older version of java which causes problems now. I found a workaround though:

https://github.com/SMILEY4/WTSightEdit/blob/release/README.md#how-to-run
