### ISSUE TITLE
Uploading Screenshot of reticle not working

### ISSUE THREAD

**Issue by Skektec** [SMILEY4/WTSightEdit#6]
Hey, so after going Create New sight > Checking the create sight metadata > selecting my vehicle > and proceeding to the upload screenshot screen I run into a issue. After selecting the screenshot in files for the reticle I click next and get "No image selected. Select at least on image to continue" but I've already selected an image.

Logs give this error:

```
( Info) 2022-04-30::21:13:37.009 (PID=18) @ScreenshotUploadLoader:20: Loading 'ScreenshotUpload' ( > CREATE_SIGHT > SELECT_CALIBRATION > SELECT_VEHICLE)
( Info) 2022-04-30::21:13:37.081 (PID=18) @ScreenshotUploadController:64: Loaded ammunition for vehicle_ussr_t_72a: 6
(ERROR) 2022-04-30::21:13:37.090 (PID=18) @ThreadGroup:1084:       Exception in thread "JavaFX Application Thread" 
(ERROR) 2022-04-30::21:13:37.344 (PID=18) @Throwable$WrappedPrintStream:763: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
(ERROR) 2022-04-30::21:13:37.344 (PID=18) @Throwable$WrappedPrintStream:763: 	at javafx.fxml@18.0.1/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857) 
```

Sorry for the bother on a old project.

**Comment by SMILEY4** [comment]
hi,
my bad, the run-command was still missing something. I updated it in the readme.

   ```
   java --module-path pathToJavaFx/lib -jar pathToWTSightEdit/data/wtedit_application.jar --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web,javafx.swt
   ```
this should work now.

thanks for reporting the issue.

**Comment by Skektec** [comment]
Hey thanks for the reply
I tried the line you sent me and got some errors so I just tried reorganizing it and it works perfectly!
Here's the line I used:
`java --module-path pathToJavaFx/lib --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web,javafx.swt -jar pathToWTSightEdit/data/wtedit_application.jar`

Thanks for all the help, youre a legend
